title: My Notes
description: A simple site for my notes using Just the Docs.
remote_theme: just-the-docs/just-the-docs
url: https://vaibhav-mattoo.github.io
color_scheme: dark
aux_links:
  GitHub: https://github.com/vaibhav-mattoo
